apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
  - helm-release.yaml
  - storageclass.yaml
  - recurringjobs-release.yaml
  - service-monitor.yaml
  - prometheus-rules.yaml
  - ingress.yaml
