---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-kube-vip
  namespace: flux-system
spec:
  path: ./kubernetes/apps/kube-system/kube-vip/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: apps/v1
      kind: DaemonSet
      name: kube-vip
      namespace: kube-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
