---
collections:
  - name: community.general
    version: 4.5.0
  - name: community.sops
    version: 1.2.0
  - name: ansible.posix
    version: 1.3.0
roles:
  - src: xanmanning.k3s
    version: v3.1.1
