---
collections:
  - name: community.general
    version: 6.0.1
  - name: community.sops
    version: 1.4.1
  - name: ansible.posix
    version: 1.4.0
  - name: ansible.utils
    version: 2.8.0
roles:
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: v3.3.1
