---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./cilium/ks.yaml
  - ./local-path-provisioner/ks.yaml
  - ./metrics-server/ks.yaml
  - ./reloader/ks.yaml
