---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-cloudflare-ddns
  namespace: flux-system
spec:
  path: ./kubernetes/apps/networking/cloudflare-ddns/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: cloudflare-ddns
      namespace: networking
  interval: 30m
  timeout: 5m
