---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: k8s-at-home
  namespace: flux-system
spec:
  interval: 30m
  url: https://k8s-at-home.com/charts/
  timeout: 3m
