---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - namespace.yaml
  # - calibre
  # - plex # Moved to nas
  - radarr
  - sabnzbd
  - shared
  - sonarr
  - bazarr

patches:
  - path: ./patch/base-helm.yaml
    target:
      kind: HelmRelease

  - path: ./patch/vpn-1.sops.yaml
    target:
      annotationSelector: "feature=vpn-1"
