[env]
_.python.venv = { path = "{{config_root}}/.venv", create = true }
KUBECONFIG = "{{config_root}}/kubeconfig"
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
TALOSCONFIG = "{{config_root}}/kubernetes/bootstrap/talos/clusterconfig/talosconfig"
TASK_X_ENV_PRECEDENCE = 1
TASK_X_MAP_VARIABLES = 0

[tasks.deps]
description = "Install dependencies"
run = "uv pip install -r requirements.txt"

[tools]
# Template tools
python = "3.13"
uv = "0.5.24"
# Operations tools
"aqua:budimanjojo/talhelper" = "3.0.16"
"aqua:cloudflare/cloudflared" = "2025.1.0"
"aqua:FiloSottile/age" = "1.2.1"
"aqua:fluxcd/flux2" = "2.4.0"
"aqua:getsops/sops" = "3.9.4"
"aqua:go-task/task" = "3.41.0"
"aqua:helm/helm" = "3.17.0"
"aqua:helmfile/helmfile" = "0.170.1"
"aqua:jqlang/jq" = "1.7.1"
"aqua:kubernetes-sigs/kustomize" = "5.6.0"
"aqua:kubernetes/kubectl" = "1.32.1"
"aqua:mikefarah/yq" = "4.45.1"
"aqua:siderolabs/talos" = "1.9.2"
"aqua:yannh/kubeconform" = "0.6.7"
