[env]
_.python.venv = { path = "{{config_root}}/.venv", create = true }
KUBECONFIG = "{{config_root}}/kubeconfig"
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
TALOSCONFIG = "{{config_root}}/talos/clusterconfig/talosconfig"
BOOTSTRAP_DIR = "{{config_root}}/bootstrap"
KUBERNETES_DIR = "{{config_root}}/kubernetes"
ROOT_DIR = "{{config_root}}"
SCRIPTS_DIR = "{{config_root}}/scripts"
TALOS_DIR = "{{config_root}}/talos"

[tools]
"python" = "3.13"
"pipx:makejinja" = "2.7.2"
"aqua:budimanjojo/talhelper" = "3.0.21"
"aqua:cilium/cilium-cli" = "0.18.3"
"aqua:cli/cli" = "2.70.0"
"aqua:cloudflare/cloudflared" = "2025.4.0"
"aqua:cue-lang/cue" = "0.12.1"
"aqua:FiloSottile/age" = "1.2.1"
"aqua:fluxcd/flux2" = "2.5.1"
"aqua:getsops/sops" = "3.10.2"
"aqua:go-task/task" = "3.42.1"
"aqua:helm/helm" = "3.17.3"
"aqua:helmfile/helmfile" = "0.171.0"
"aqua:jqlang/jq" = "1.7.1"
"aqua:kubernetes-sigs/kustomize" = "5.6.0"
"aqua:kubernetes/kubectl" = "1.32.3"
"aqua:mikefarah/yq" = "4.45.1"
"aqua:siderolabs/talos" = "1.9.5"
"aqua:yannh/kubeconform" = "0.6.7"
