[makejinja]
inputs = ["./bootstrap/templates"]
output = "./"
exclude_patterns = [".mjfilter.py", "*.partial.yaml.j2"]
data = ["./bootstrap/vars/config.yaml"]
import_paths = ["./bootstrap/scripts"]
loaders = ["plugin:Plugin"]
jinja_suffix = ".j2"
force = true
undefined = "chainable"

# Block and comment delimiters are changed to avoid conflicts with Renovate
# Variable delimiters are changed to avoid conflicts with Renovate and Go templates
# https://github.com/renovatebot/renovate/discussions/18470
[makejinja.delimiter]
block_start = "#%"
block_end = "%#"
comment_start = "#|"
comment_end = "|#"
variable_start = "#{"
variable_end = "}#"
