[env]
_.python.venv = { path = "{{config_root}}/.venv", create = true }
KUBECONFIG = "{{config_root}}/kubeconfig"
PYTHONDONTWRITEBYTECODE = "1"
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
TALOSCONFIG = "{{config_root}}/kubernetes/bootstrap/talos/clusterconfig/talosconfig"
TASK_X_ENV_PRECEDENCE = 1
TASK_X_MAP_VARIABLES = 0

[tasks.install]
description = "Install Python dependencies"
run = "uv pip install -r requirements.txt"

[tools]
python = "3.13"
"aqua:astral-sh/uv" = "latest"
"aqua:budimanjojo/talhelper" = "latest"
"aqua:cloudflare/cloudflared" = "latest"
"aqua:FiloSottile/age" = "latest"
"aqua:fluxcd/flux2" = "latest"
"aqua:getsops/sops" = "latest"
"aqua:go-task/task" = "latest"
"aqua:helm/helm" = "latest"
"aqua:helmfile/helmfile" = "latest"
"aqua:jqlang/jq" = "latest"
"aqua:kubernetes-sigs/kustomize" = "latest"
"aqua:kubernetes/kubectl" = "latest"
"aqua:mikefarah/yq" = "latest"
"aqua:siderolabs/talos" = "latest"
"aqua:stern/stern" = "latest"
"aqua:yannh/kubeconform" = "latest"
