---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: dysnix-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://dysnix.github.io/charts
  timeout: 2m
