---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: fairwinds
  namespace: flux-system
spec:
  interval: 30m
  url: https://charts.fairwinds.com/stable
  timeout: 3m
