---
# https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/
# https://github.com/PyratLabs/ansible-role-k3s

# (bool) Specify if a host (or host group) are part of the control plane
k3s_control_node: true

# (dict) k3s settings for all control-plane nodes
k3s_server:
  node-ip: "{{ ansible_host }}"
  tls-san:
    - "{{ kubevip_address }}"
  https-listen-port: 6443
  docker: false                    # Disable Docker - this will use the default containerd CRI
  flannel-backend: "none"          # This needs to be in quotes
  disable:
    - flannel                      # Disable flannel - replaced with Calico
    - local-storage                # Disable local-path-provisioner - installed with Flux
    - metrics-server               # Disable metrics-server - installed with Flux
    - servicelb                    # Disable servicelb - replaced with metallb and installed with Flux
    - traefik                      # Disable traefik - replaced with ingress-nginx and installed with Flux
  disable-network-policy: true
  disable-cloud-controller: true
  disable-kube-proxy: true         # Disable kube-proxy - replaced with Calico eBPF
  write-kubeconfig-mode: "644"
  cluster-cidr: "10.42.0.0/16"     # Network CIDR to use for pod IPs
  service-cidr: "10.43.0.0/16"     # Network CIDR to use for service IPs
  kube-controller-manager-arg:
    - "bind-address=0.0.0.0"       # Required to monitor kube-controller-manager with kube-prometheus-stack
  kube-scheduler-arg:
    - "bind-address=0.0.0.0"       # Required to monitor kube-scheduler with kube-prometheus-stack
  etcd-expose-metrics: true        # Required to monitor etcd with kube-prometheus-stack
  kube-apiserver-arg:
    - "anonymous-auth=true"        # Required for HAProxy health-checks
