---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: authentik-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://charts.goauthentik.io/
  timeout: 3m
