---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: descheduler-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://kubernetes-sigs.github.io/descheduler
  timeout: 3m
