---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/vmware-tanzu/helm-charts/velero-2.27.5/charts/velero/crds/backups.yaml
  - https://raw.githubusercontent.com/vmware-tanzu/helm-charts/velero-2.27.5/charts/velero/crds/backupstoragelocations.yaml
  - https://raw.githubusercontent.com/vmware-tanzu/helm-charts/velero-2.27.5/charts/velero/crds/deletebackuprequests.yaml
  - https://raw.githubusercontent.com/vmware-tanzu/helm-charts/velero-2.27.5/charts/velero/crds/downloadrequests.yaml
  - https://raw.githubusercontent.com/vmware-tanzu/helm-charts/velero-2.27.5/charts/velero/crds/podvolumebackups.yaml
  - https://raw.githubusercontent.com/vmware-tanzu/helm-charts/velero-2.27.5/charts/velero/crds/podvolumerestores.yaml
  - https://raw.githubusercontent.com/vmware-tanzu/helm-charts/velero-2.27.5/charts/velero/crds/resticrepositories.yaml
  - https://raw.githubusercontent.com/vmware-tanzu/helm-charts/velero-2.27.5/charts/velero/crds/restores.yaml
  - https://raw.githubusercontent.com/vmware-tanzu/helm-charts/velero-2.27.5/charts/velero/crds/schedules.yaml
  - https://raw.githubusercontent.com/vmware-tanzu/helm-charts/velero-2.27.5/charts/velero/crds/serverstatusrequests.yaml
  - https://raw.githubusercontent.com/vmware-tanzu/helm-charts/velero-2.27.5/charts/velero/crds/volumesnapshotlocations.yaml
