---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: chain-no-auth-local
  namespace: networking
spec:
  chain:
    middlewares:
      - name: middlewares-rate-limit
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: chain-no-auth
  namespace: networking
spec:
  chain:
    middlewares:
      - name: middlewares-rate-limit
      - name: middlewares-secure-headers
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: chain-basic-auth
  namespace: networking
spec:
  chain:
    middlewares:
      - name: middlewares-rate-limit
      - name: middlewares-secure-headers
      - name: middlewares-basic-auth
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: chain-authentik
  namespace: networking
spec:
  chain:
    middlewares:
      - name: middlewares-rate-limit
      - name: middlewares-secure-headers
      - name: middlewares-authentik
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: chain-authelia
  namespace: networking
spec:
  chain:
    middlewares:
      - name: middlewares-rate-limit
      - name: middlewares-secure-headers
        #- name: middlewares-authelia
---
