apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - guacamole.yaml
  - vaultwarden.yaml # this has been migrated to k3s so no longer needs to point to ruri
  - proxmox.yaml
  - synology-dsm.yaml
  - synology-moments.yaml
  - synology-drive.yaml
  - portainer.yaml
  - phpmyadmin.yaml
  - plex.yaml
  - omoikane-ldap.yaml
