---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-k8s-gateway
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-metallb
    - name: cluster-apps-metallb-config
  path: ./kubernetes/apps/networking/k8s-gateway/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: k8s-gateway
      namespace: networking
  interval: 30m
  retryInterval: 1m
  timeout: 3m
