#ENC[AES256_GCM,data:8UXvtbKapQc=,iv:C6zwSgQ5cODXZK2zQuUQjzRPJVDMNWb+/KnWOIMx+aY=,tag:rGo1M30yREGNSubqV+Hqtw==,type:comment]
generic__domain_name: ENC[AES256_GCM,data:s0t1AHp8OER4f8ZFr+E=,iv:Bpd+PVcdDVIeO5cL5h+ypqhVKnkhiOyLTPM7JFHy314=,tag:MaeVQeh9A4fQ/B0sunH2ZA==,type:str]
generic__organization_name: ENC[AES256_GCM,data:wlKr8FL07p/a3g==,iv:LRXacFA2ayIarvxB8w9S2Lkh4l7vgMWuQQf3pVjmyFU=,tag:wtAqEZWmgjQnY3d2Uf1Xlw==,type:str]
#ENC[AES256_GCM,data:bvF/JgA=,iv:6ohFEwjJlQz9gG8+WubBFTVdvlGrdfUkOrAIBsITIqQ=,tag:Z8ZseSFvJfr6NDNrdbbw9w==,type:comment]
#ENC[AES256_GCM,data:NGV9sX8OBt14ksmb,iv:cTERZDGS/d+ovcy30xhrK4WTXuYZgJQAui/IKwbKgsI=,tag:beSZg2VCYmmfOfrhoP13Lg==,type:comment]
apps_cloudflare_email: ENC[AES256_GCM,data:ruJrArRjGs3sEWO4D3hi3YevTDiGr/sP,iv:jmTdZKhvHf4iMMjwNw7LOiqFkKlGvr4+8myRTLEtAO0=,tag:xvNgJunTCd1GmPObJNaSFg==,type:str]
apps__cloudflare_api_token: ENC[AES256_GCM,data:aieSwhsRuq4zfO2Lpf8BlfCi7Rc082p507aGv7Wz/0AFFLb0gMWmmw==,iv:NKTtCvF789JDdVz3tTM21HoNXkz8yG4M6lqc2jx2wNM=,tag:y9T8hPP6ae6KHijfiY4Gvw==,type:str]
apps__cloudflare_domain_1_fqdn: ENC[AES256_GCM,data:AIJRErwDsji8wyolcbY=,iv:Jr/OkD0djXq1k1yE01g1zpEjjwKaLe8l24xbVEvzMz0=,tag:UfvCs1qexiU4VgwMH2AbeQ==,type:str]
apps__cloudflare_domain_1_zone_id: ENC[AES256_GCM,data:imUGalb7ET8hzDjIl4ObMSlJfoFJmR+LfJs8Fbv/voI=,iv:fDukJ+yAi0v/5hmi3cH8U9yvU8xCyru//3uTAgegXEs=,tag:GkzAmS3vr90L+Ni/KXbEQw==,type:str]
apps__cloudflare_domain_1_obfuscated_fqdn: ENC[AES256_GCM,data:tQ2soLZHHwQq86/xy5dcApGv3swZYAjZQ+iIyEK7G7XcElwucDb6to7XGLzvTdA=,iv:9ly0pDd18Kd9XC+a6HIPzILgExESAsapdEW42n3ai3M=,tag:0Z8uiwHrHNMZp6DZ4aw+xw==,type:str]
#ENC[AES256_GCM,data:BmWmOjzwnA==,iv:b8uWKyMQNrB9rffTDF0ws1pumrbEQNLoUoyCZu6JBZI=,tag:Rbtxhfsns17lA6RQDt7sBA==,type:comment]
apps__unifi_db_password: ENC[AES256_GCM,data:/BgDY8rRlvITLK9jG0S4MlkbL7vv5PJeS840Oer3z1chW0HmEDCOJ11nFLM0KgydONP5qVBJfUlWdZxZJBln6Q==,iv:eW2Q4stryDEyngm9yVNJy3ANQD33WXtlaM0TGwsKpzw=,tag:rBjUgwRsqIF1rJ8mMCt5WA==,type:str]
#ENC[AES256_GCM,data:9umDwZRGaxQ5/7YYC6o=,iv:Xf8hEH/uSmKpDUppR0F1bLfbS8tE02yxaXvJjs+l8Ak=,tag:8ZIybt8fyGpGVB1pnlk1fA==,type:comment]
apps__oauth2_proxy_whitelist_domains: ENC[AES256_GCM,data:hbWWrIrfqWqYtezu7Pul,iv:D2FoizAMavQCjWOOCJMmwa4OaGPkmUaUiDZNqqzp/TI=,tag:CJjs8/G4F/wNplxQprMk/Q==,type:str]
apps__oauth2_proxy_client_id: ENC[AES256_GCM,data:GFZEq9UUNop47UXJA/RPop8wMzE=,iv:KfOkRszuivWEP1EeiaZbjowk0+63FLsBBNNQqrGmLD8=,tag:zvou2f6/qODvN6WBbZ8USg==,type:str]
apps__oauth2_proxy_client_secret: ENC[AES256_GCM,data:qaV4nSBzDr2NLJok5zsjg3HJYidzoKFKrD1RM/9yGdAADFMX+0jV0Q==,iv:C0KcbCnscteE0hQlDZhfQPRRx61WYpC4b2DDaRG00Ec=,tag:O9Y8Llz4SasMcJPiYXJ61A==,type:str]
apps__oauth2_proxy_cookie_secret: ENC[AES256_GCM,data:ek5S8J0p7MRUD+a9WEE88LPTE3+MTPGuyO1WgX4IHxs=,iv:Kpr+kPyiHCM5/xgNRXhqbNEpsi+jJ2pA4Vz8Bu7PpsY=,tag:CF2pAtooe+A5l7GsTnvm/w==,type:str]
apps__oauth2_proxy_cookie_name: ENC[AES256_GCM,data:V16RVHRS0ME7TIYVaKWssmVK,iv:o8VbGFbQcyGJLFmFigqf7ZLp80TvqyQd837rbvY5c4Y=,tag:pxFUdZWv9WaosWaqkPBzGA==,type:str]
apps__oauth2_proxy_redirect_url: ENC[AES256_GCM,data:0g5EDbI4Loc5tuikOExIFYMHrQRT+i5CUj4CrzV5V6mjydZ6egC90gR6/w==,iv:++nfT13CX4uwvd8/Yz8w+gE8w+xOwx8n6Dy5I58mgfU=,tag:0CjCcXo8YxY5dlM+uwtg8A==,type:str]
apps__oauth2_proxy_azure_tenant_id: ENC[AES256_GCM,data:uoVBVBIBsZhnEqHuDA4WtHKxzMFepDiw1OTvszjTTMnY8O8V,iv:xB6KwfHkhfUbp4zWo2k5zpKPZMg6ZYr0Cnw32qqiXSI=,tag:/AfRzBln4JyS69ZrrDUyhg==,type:str]
apps__oauth2_proxy_azure_client_id: ENC[AES256_GCM,data:+75lW2geAiL5wFwbsTSBfLSt+VG2LZzUH5rexybguJVTzTeV,iv:PNUScnavwTrGE7asOtxxtuzEVZjw+iTQl+TZhtlD0us=,tag:TaDFlwpWGUfUAhM2mndR8Q==,type:str]
apps__oauth2_proxy_azure_client_secret: ENC[AES256_GCM,data:Pam/LAaXVj7M/7Exq8WiBoYqDsWe1i9D91PIe68ps5H+CqJ1nhXJSQ==,iv:oVNGIzoWVw1Bq5eaaGcNfZqIFzGpANJ29hpidD+sv8U=,tag:G5HO0XK9QMzoGevfz1G78w==,type:str]
apps__oauth2_proxy_azure_email_domain: ENC[AES256_GCM,data:w06+W+if2MKQXKPjczw=,iv:Ig02A3ZHvEiYexkJ6qM5YVsqxxQix7Q210nEV6mPqQ0=,tag:1yIMhepInB3O4uXO2Ifw0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182vhhzupcql0c9l272gm3z004x7hnukt7ptugwqwrqnh2slyu9zskphzdk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDT1RYWUFvZE9UQkcwb1Nx
            M2U4WUxwdi9JVVJlUzZFWWlkOXY5ejM0MUhNClJ0NUhQYjlWb3VIYmgra0dUWnhW
            ZU5JdVdYSzBXSExmbjN6cEZJMUtOYUkKLS0tIDdGTi9md1F2WHRtMVpXMUhSK2hI
            eVBKRXVRTE0xSGdTQzF6enJtNnMzOGcKfIhR/2B8E7FhoP5b+fRdpPwIwE7gOrIa
            mR6EnBhQi6Cr/LM/7nwWvCt/E/2IoDLMPPl7f1xyDPIjV/fY5XncqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-24T21:27:39Z"
    mac: ENC[AES256_GCM,data:+8132LGnL3sk86SO/+UvhGYsEdXBU+ulJFxZJSliuJV/mEJaekHjGcYngReLiodnaJoA9gLxDAh5pAUYnm1vtRXdMD3QcIgnOEbYRDul78ZU5f28oMuTSI2LKBbQsu8a6k4VChrMA0GEqwuBWVOcTYoTWmPniw34bvkD2/RsPNA=,iv:baFtnKY4DTd7aQEmb/XU5YX5HdEW6pTbvWrro3E602c=,tag:or/1r5HvjrVbHb6U72k1Cg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
