---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: calibre
      version: 5.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  install:
    remediation:
      retries: 3

  values:
    # https://github.com/k8s-at-home/charts/blob/master/charts/stable/calibre/values.yaml
    image:
      repository: linuxserver/calibre-web
      tag: version-0.6.20

    podAnnotations:
      backup.velero.io/backup-volumes: config

    env:
      PGID: "1000"
      PUID: "1000"

    podSecurityContext:
      # runAsUser: 1000
      # runAsGroup: 1000
      supplementalGroups:
        - 100
        # - 568

    initContainers:
      update-config-ownership:
        image: busybox:1.36.1
        command: ["sh", "-c", "chown -R 1000:1000 /config"]
        volumeMounts:
          - name: config
            mountPath: /config
        securityContext:
          runAsUser: 0
      update-config-permission:
        image: busybox:1.36.1
        command: ["sh", "-c", "chmod -R 774 /config"]
        volumeMounts:
          - name: config
            mountPath: /config
        securityContext:
          runAsUser: 0

    # Pod
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "250m"

    # Persistence
    persistence:
      # Make sure it has pid/gid 568
      # and it is pre-populated
      config:
        enabled: true
        existingClaim: calibre
      books:
        enabled: true
        existingClaim: book
        mountPath: /books

    # Linuxserver's calibre has their port at 8083
    service:
      main:
        ports:
          http:
            port: 8083

    # Network
    ingress:
      main:
        enabled: true
        annotations:
          coredns.io/hostname: &host "calibre.home.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/icon: "book"
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8"
        hosts:
          - host: *host
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: calibre-tls
