---
# https://rancher.com/docs/k3s/latest/en/installation/install-options/agent-config/
# https://github.com/PyratLabs/ansible-role-k3s

# (bool) Specify if a host (or host group) are part of the control plane
k3s_control_node: false

# (dict) k3s settings for all worker nodes
k3s_agent:
  node-ip: "{{ ansible_host }}"
