---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex
  namespace: networking
  annotations:
    hajimari.io/enable: "true"
    hajimari.io/icon: mdi:plex
    coredns.io/hostname: "plex.${SECRET_DOMAIN}"
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    #traefik.ingress.kubernetes.io/router.middlewares: networking-traefik-middleware-chains-authentik@kubernetescrd
    traefik.ingress.kubernetes.io/router.middlewares: networking-traefik-middleware-chains-authelia@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: "plex.${SECRET_DOMAIN}"
      http:
        paths:
          - backend:
              service:
                name: plex
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - "plex.${SECRET_DOMAIN}"
      secretName: "plex-${SECRET_DOMAIN/./-}-tls"
---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: networking
spec:
  ports:
    - name: https
      port: 80
      protocol: TCP
      targetPort: 32400
---
apiVersion: v1
kind: Endpoints
metadata:
  name: plex
  namespace: networking
subsets:
  - addresses:
      - ip: ${PLEX_ADDR}
    ports:
      - name: https
        port: 32400
