# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: longhorn-system
#   labels:
#     kustomize.toolkit.fluxcd.io/prune: "true"
#     goldilocks.fairwinds.com/enabled: "true"
# spec:
#   finalizers:
#     - foregroundDeletion
