---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./cloudflare-ddns/ks.yaml
  - ./external-dns/ks.yaml
  - ./ingress-nginx/ks.yaml
  - ./k8s-gateway/ks.yaml
  - ./metallb/ks.yaml
