---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    remediation:
      retries: 3
  dependsOn:
    - name: sabnzbd
      namespace: media

  values:
    # https://github.com/k8s-at-home/charts/blob/master/charts/stable/sonarr/values.yaml
    image:
      repository: linuxserver/sonarr
      tag: 3.0.10

    # Backup
    podAnnotations:
      # secret.reloader.stakater.com/reload: home-assistant-secrets
      # k8s.v1.cni.cncf.io/networks: macvlan-static-iot-hass
      backup.velero.io/backup-volumes: config

    env:
      PGID: "1000"
      PUID: "1000"

    podSecurityContext:
      # runAsUser: 1000
      # runAsGroup: 1000
      supplementalGroups:
        - 100
        # - 568

    initContainers:
      update-config-ownership:
        image: busybox:1.36.1
        command: ["sh", "-c", "chown -R 1000:1000 /config"]
        volumeMounts:
          - name: config
            mountPath: /config
        securityContext:
          runAsUser: 0
      update-config-permission:
        image: busybox:1.36.1
        command: ["sh", "-c", "chmod -R 774 /config"]
        volumeMounts:
          - name: config
            mountPath: /config
        securityContext:
          runAsUser: 0

    # Pod
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "250m"

    # Persistence
    persistence:
      # Make sure it has pid/gid 568
      # and it is pre-populated
      config:
        enabled: true
        existingClaim: sonarr
      downloads:
        enabled: true
        existingClaim: download
        mountPath: /downloads
      tv:
        enabled: true
        existingClaim: tv
        mountPath: /tv

    service:
      main:
        enabled: true
        ports:
          http:
            port: 8989

    ingress:
      main:
        enabled: true
        annotations:
          coredns.io/hostname: &host "sonarr.${SECRET_DOMAIN}"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "television"
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8"
        hosts:
          - host: *host
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: sonarr-tls
