---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-ingress-traefik
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-cert-manager
    - name: cluster-apps-cert-manager-issuers
    - name: cluster-apps-metallb
    - name: cluster-apps-metallb-config
  path: ./kubernetes/apps/networking/traefik/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: traefik
      namespace: networking
  interval: 30m
  retryInterval: 1m
  timeout: 1m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-add-ons
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/apps/networking/traefik/add-ons
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  # dependsOn:
  #   - name: cluster-apps-ingress-traefik
  healthChecks:
    - apiVersion: traefik.containo.us/v1alpha1
      kind: TLSStore
      name: default
      namespace: networking
  prune: true
  wait: true
  interval: 30m
  retryInterval: 2m
  timeout: 1m
