---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  # NOTE: Only enable system-upgrade-controller if you also update the version of k3s in the following file
  # otherwise if you run ansible against an already provisioned cluster you might downgrade it
  # https://github.com/onedr0p/flux-cluster-template/blob/main/ansible/inventory/group_vars/kubernetes/main.yaml
  # - ./system-upgrade-controller/ks.yaml
