---
# https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/
# https://github.com/PyratLabs/ansible-role-k3s

# (bool) Specify if a host (or host group) are part of the control plane
k3s_control_node: true

# (dict) k3s settings for all control-plane nodes
k3s_server:
  node-ip: "{{ ansible_host }}"
  tls-san:
    # kube-vip
    - "{{ kubevip_address }}"
  docker: false
  flannel-backend: "host-gw" # This needs to be in quotes
  disable:
    - traefik
    - servicelb
    - metrics-server
  disable-network-policy: true
  disable-cloud-controller: true
  write-kubeconfig-mode: "644"
  # Network CIDR to use for pod IPs
  cluster-cidr: "10.42.0.0/16"
  # Network CIDR to use for service IPs
  service-cidr: "10.43.0.0/16"
  kubelet-arg:
    - "feature-gates=GracefulNodeShutdown=true"
    - "feature-gates=MixedProtocolLBService=true"
  # Required to use monitor these components with kube-prometheus-stack
  kube-controller-manager-arg:
    - "address=0.0.0.0"
    - "bind-address=0.0.0.0"
  kube-proxy-arg:
    - "metrics-bind-address=0.0.0.0"
  kube-scheduler-arg:
    - "address=0.0.0.0"
    - "bind-address=0.0.0.0"
  etcd-expose-metrics: true
  # Required for HAProxy health-checks
  kube-apiserver-arg:
    - "anonymous-auth=true"
