---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m

  install:
    remediation:
      retries: 3

  values:
    image:
      repository: plexinc/pms-docker
      tag: 1.32.6.7468-07e0d4a7e

    # Backup
    podAnnotations:
      backup.velero.io/backup-volumes: config

    podSecurityContext: # Plex container runAS plex:plex (1000:1000)
      # runAsUser: 1000
      # runAsGroup: 1000
      # fsGroup: 1000
      # fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 44 # video
        - 100 # users

    initContainers:
      update-volume-permission:
        image: busybox:1.36.1
        command: ["sh", "-c", "chown -R 1000:1000 /config"]
        volumeMounts:
          - name: config
            mountPath: /config
        securityContext:
          runAsUser: 0

    # Pod
    resources:
      requests:
        cpu: 100m
        gpu.intel.com/i915: 1
        memory: 4282M
      limits:
        gpu.intel.com/i915: 1
        memory: 12G

    # Persistence
    persistence:
      # Make sure it has pid/gid 568
      # and it is pre-populated
      config:
        enabled: true
        existingClaim: plex
      movies:
        enabled: true
        existingClaim: movie
        mountPath: /movies
      tv:
        enabled: true
        existingClaim: tv
        mountPath: /tv
      transcode:
        enabled: true
        type: emptyDir

    # Network
    hostNetwork: true
    service:
      main:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: 10.0.6.228
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: plex
          coredns.io/hostname: "plex.home.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/icon: "cast"
        ports:
          http:
            port: 32400
