# ---
# apiVersion: traefik.containo.us/v1alpha1
# kind: Middleware
# metadata:
#   name: traefik-middleware-authentik
#   namespace: networking
# spec:
#   forwardAuth:
#     address: http://authentik/outpost.goauthentik.io/auth/traefik
#     trustForwardHeader: true
#     authResponseHeaders:
#       - X-authentik-username
#       - X-authentik-groups
#       - X-authentik-email
#       - X-authentik-name
#       - X-authentik-uid
#       - X-authentik-jwt
#       - X-authentik-meta-jwks
#       - X-authentik-meta-outpost
#       - X-authentik-meta-provider
#       - X-authentik-meta-app
#       - X-authentik-meta-version
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-custom-headers
  namespace: networking
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: https
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-basic-auth
  namespace: networking
spec:
  basicAuth:
    secret: basic-auth
    #removeHeader: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-error-pages
  namespace: networking
spec:
  errors:
    status:
      - "300-300"
      - "303-306"
      - "308-599"
    query: /{status}.html
    service:
      name: error-pages
      port: 8080
---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-redirect-https
  namespace: networking
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-cloudflare-ips
  namespace: networking
spec:
  ipWhiteList:
    sourceRange:
      - 173.245.48.0/20
      - 103.21.244.0/22
      - 103.22.200.0/22
      - 103.31.4.0/22
      - 141.101.64.0/18
      - 108.162.192.0/18
      - 190.93.240.0/20
      - 188.114.96.0/20
      - 197.234.240.0/22
      - 198.41.128.0/17
      - 162.158.0.0/15
      - 104.16.0.0/13
      - 104.24.0.0/14
      - 172.64.0.0/13
      - 131.0.72.0/22
      - 2400:cb00::/32
      - 2606:4700::/32
      - 2803:f800::/32
      - 2405:b500::/32
      - 2405:8100::/32
      - 2a06:98c0::/29
      - 2c0f:f248::/32
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-local-ips
  namespace: networking
spec:
  ipWhiteList:
    sourceRange:
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16
      - 169.254.0.0/16
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-github-hooks-ips
  namespace: networking
spec:
  ipWhiteList:
    # https://api.github.com/meta
    sourceRange:
      - 192.30.252.0/22
      - 185.199.108.0/22
      - 140.82.112.0/20
      - 143.55.64.0/20
      - 2a0a:a440::/29
      - 2606:50c0::/32
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-rate-limit
  namespace: networking
spec:
  rateLimit:
    average: 100
    burst: 50
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-secure-headers
  namespace: networking
spec:
  headers:
    accessControlAllowMethods:
      - GET
      - OPTIONS
      - PUT
    accessControlMaxAge: 100
    hostsProxyHeaders:
      - "X-Forwarded-Host"
      - "X-Forwarded-For"
      - "X-Forwarded-Proto"
      - "X-GEO-City"
      - "Cf-Connecting-Ip"
      - "Cf-Ipcountry"
    stsSeconds: 63072000
    stsIncludeSubdomains: true
    stsPreload: true
    forceSTSHeader: true
    customFrameOptionsValue: "allow-from https:${SECRET_DOMAIN}" #CSP takes care of this but may be needed for organizr.
    contentTypeNosniff: true
    browserXssFilter: true
    referrerPolicy: "origin-when-cross-origin"
    #referrerPolicy: "same-origin"
    # Setting contentSecurityPolicy is more secure but it can break things. Proper auth will reduce the risk.
    # the below line also breaks some apps due to 'none' - sonarr, radarr, etc.
    # contentSecurityPolicy: "frame-ancestors '*.example.com:*';object-src 'none';script-src 'none';"
    permissionsPolicy: "camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none';"
    customResponseHeaders:
      X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex,"
    # permissionsPolicy: "camera=(), microphone=(), geolocation=(), payment=(), usb=(), vr=()"
    # customResponseHeaders:
    #   X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex,"
    #   City: X-GEO-City
    #   server: ""
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-forward-auth
  namespace: networking
spec:
  forwardAuth:
    address: http://traefik-forward-auth:4181
    trustForwardHeader: true
    authResponseHeaders:
      - X-Forwarded-User
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-authelia
  namespace: networking
  labels:
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/name: authelia
spec:
  forwardAuth:
    #address: http://authelia-external.authelia.svc.cluster.local/api/verify?rd=https://auth.${SECRET_DOMAIN}
    #address: http://authelia.networking.svc.cluster.local/api/verify?rd=https://authelia.${SECRET_DOMAIN}
    address: http://authelia.networking.svc.cluster.local:9091/api/verify?rd=https%3A%2F%2Fauthelia.${SECRET_DOMAIN}%2F
    trustForwardHeader: true
    authResponseHeaders:
      - Remote-User
      - Remote-Groups
      - Remote-Name
      - Remote-Email
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-chains-default
  namespace: networking
spec:
  chain:
    middlewares:
      - name: traefik-middleware-redirect-https
      #- name: traefik-middleware-local-ips
      # - name: traefik-middleware-cloudflare-ips
      - name: traefik-middleware-rate-limit
      - name: traefik-middleware-secure-headers
      #- name: traefik-middleware-error-pages
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-plex-addprefix
  namespace: networking
spec:
  addPrefix:
    prefix: "/web"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-chains-basic-auth
  namespace: networking
spec:
  chain:
    middlewares:
      - name: traefik-basic-auth
      - name: traefik-middleware-redirect-https
      - name: traefik-middleware-secure-headers
      - name: traefik-middleware-rate-limit
      - name: traefik-middleware-error-pages
# ---
# apiVersion: traefik.containo.us/v1alpha1
# kind: Middleware
# metadata:
#   name: traefik-middleware-chains-authentik
#   namespace: networking
# spec:
#   chain:
#     middlewares:
#       - name: traefik-middleware-redirect-https
#       - name: traefik-middleware-secure-headers
#       - name: traefik-middleware-rate-limit
#       - name: traefik-middleware-authentik
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-chains-authelia
  namespace: networking
spec:
  chain:
    middlewares:
      - name: traefik-middleware-redirect-https
      - name: traefik-middleware-secure-headers
      - name: traefik-middleware-rate-limit
      # - name: traefik-middleware-local-ips
      # - name: traefik-middleware-cloudflare-ips
      - name: traefik-middleware-authelia
      - name: traefik-middleware-error-pages
# ---
# apiVersion: traefik.containo.us/v1alpha1
# kind: Middleware
# metadata:
#   name: traefik-middleware-chains-authentik-plex
#   namespace: networking
# spec:
#   chain:
#     middlewares:
#       - name: traefik-middleware-rate-limit
#       - name: traefik-middleware-redirect-https
#       - name: traefik-middleware-plex-addprefix
#       - name: traefik-middleware-secure-headers
#       - name: traefik-middleware-authentik
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-chains-forwardauth
  namespace: networking
spec:
  chain:
    middlewares:
      - name: traefik-middleware-redirect-https
      - name: traefik-middleware-secure-headers
      - name: traefik-middleware-rate-limit
      - name: traefik-middleware-forward-auth
