---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Mise"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # once a week
jobs:
  mise:
    name: upgrade-tools
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup mise
        uses: jdx/mise-action@7a111ead46986ccad89a74ad013ba2a7c08c9e67 # v2.2.1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Upgrade dependencies
        run: mise upgrade --bump

      - name: Get diff of .mise.toml
        run: |
          git diff > diff.patch

      - name: Generate Diff
        id: diff
        run: |
          cat diff.patch;
          {
              echo 'diff<<EOF'
              cat diff.patch
              echo EOF
          } >> "$GITHUB_OUTPUT";
          {
              echo "### Diff"
              echo '```diff'
              cat diff.patch
              echo '```'
          } >> "$GITHUB_STEP_SUMMARY";
          rm diff.patch

      - if: ${{ steps.diff.outputs.diff != '' }}
        name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          title: "chore(mise): upgrade dependencies"
          commit-message: "chore(mise): upgrade dependencies"
          branch: "mise-upgrade-dependencies"
          body: |
            Upgraded dependencies found in `.mise.toml`:

            ```diff
            ${{ steps.diff.outputs.diff }}
            ```

            > [!TIP]
            > Merge this pull request and then run `mise upgrade --bump` on your workstation.
